services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.5-alpine
    environment:
      - CLICKHOUSE_USER=chuser
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=chpassword
    ports:
      - "8123:8123"
    healthcheck:
      test: ["CMD", "wget", "--spider", "--tries=1", "http://chuser:chpassword@localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  api-service:
    build:
      context: .
      dockerfile: Dockerfile.py
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      clickhouse:
        condition: service_healthy

volumes:
  clickhouse_data:
    driver: local
